users:
  <USERNAME>:
    password: <PASSWORD> # docker run --rm -it johnstarich/bcrypt -P
    groups:
      - 'admins'
      - 'dev'
  <USERNAME2>:
    password: <PASSWORD> # docker run --rm -it johnstarich/bcrypt -P
    groups:
      - 'readonly'
      - 'dev'